import os

from fastapi import APIRouter, Body, Depends
from fastapi.responses import JSONResponse

from app.auth.jwt_auth import get_current_user
from app.models.health_call import HealthCallRequestModel
from agents.tools.farmer_animal_backends import create_health_call_api
from helpers.utils import get_logger

logger = get_logger(__name__)

router = APIRouter(prefix="/health-call", tags=["health-call"])


@router.post("/")
async def book_health_call(
    request: HealthCallRequestModel = Body(...),
    user_info: dict = Depends(get_current_user),
):
    """
    Direct endpoint for creating a health call booking.
    Returns the ticket number generated by the upstream API.
    """
    logger.info("[YASHhhhhhhhhhh]begin book_health_call")
    token = os.getenv("PASHUGPT_TOKEN")
    if not token:
        logger.error("PASHUGPT_TOKEN is not set")
        return JSONResponse(
            {"status": "error", "message": "PASHUGPT_TOKEN is not configured."},
            status_code=500,
        )

    try:
        response = await create_health_call_api(request, token)
    except Exception as e:
        logger.exception("Health call booking failed: %s", str(e))
        return JSONResponse(
            {"status": "error", "message": "Health call booking failed", "detail": str(e)},
            status_code=500,
        )

    if response is None:
        return JSONResponse(
            {"status": "error", "message": "Unable to create health call at the moment."},
            status_code=500,
        )

    return JSONResponse(
        {
            "status": "success",
            "ticket_number": response.ticket_number,
            "raw": response.model_dump(),
        },
        status_code=200,
    )
